# Generated by Django 3.1.4 on 2020-12-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KprcCorporation',
            fields=[
                ('corporate_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('corporation_name', models.CharField(max_length=30)),
                ('discount', models.SmallIntegerField()),
                ('registration_number', models.BigIntegerField()),
            ],
            options={
                'db_table': 'kprc_corporation',
            },
        ),
        migrations.CreateModel(
            name='KprcCustomer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_fname', models.CharField(max_length=20)),
                ('cust_lname', models.CharField(max_length=20)),
                ('cust_street', models.CharField(max_length=20)),
                ('cust_city', models.CharField(max_length=15)),
                ('cust_state', models.CharField(max_length=15)),
                ('cust_email', models.CharField(max_length=30)),
                ('cust_phone', models.BigIntegerField()),
                ('cust_type', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'kprc_customer',
            },
        ),
        migrations.CreateModel(
            name='KprcCustUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_user_id', models.SmallIntegerField()),
                ('cust_user_name', models.CharField(max_length=20)),
                ('cust_user_password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'kprc_cust_user',
            },
        ),
        migrations.CreateModel(
            name='KprcInvoice',
            fields=[
                ('invoice_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'kprc_invoice',
            },
        ),
        migrations.CreateModel(
            name='KprcLocation',
            fields=[
                ('location_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.BigIntegerField()),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
            ],
            options={
                'db_table': 'kprc_location',
            },
        ),
        migrations.CreateModel(
            name='KprcVehicleclass',
            fields=[
                ('class_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=20)),
                ('rental_rate', models.IntegerField()),
                ('over_mileage_fee', models.IntegerField()),
                ('daily_limit', models.IntegerField()),
            ],
            options={
                'db_table': 'kprc_vehicleclass',
            },
        ),
        migrations.CreateModel(
            name='KprcIndividual',
            fields=[
                ('cust', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customer.kprccustomer')),
                ('dl_number', models.CharField(max_length=30)),
                ('insurance_company', models.CharField(max_length=30)),
                ('policy_number', models.BigIntegerField()),
            ],
            options={
                'db_table': 'kprc_individual',
            },
        ),
        migrations.CreateModel(
            name='KprcVehicle',
            fields=[
                ('vin', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('license_plate_number', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.DateTimeField()),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='customer.kprcvehicleclass')),
            ],
            options={
                'db_table': 'kprc_vehicle',
            },
        ),
        migrations.CreateModel(
            name='KprcRentalService',
            fields=[
                ('pickup_date', models.DateTimeField()),
                ('dropoff_date', models.DateTimeField()),
                ('start_odometer', models.IntegerField()),
                ('end_odometer', models.IntegerField()),
                ('daily_limit', models.IntegerField()),
                ('rental_service_id', models.FloatField(primary_key=True, serialize=False)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.kprccustomer')),
                ('dropoff_location', models.ForeignKey(db_column='dropoff_location', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dropoff', to='customer.kprclocation')),
                ('pickup_location', models.ForeignKey(db_column='pickup_location', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickup', to='customer.kprclocation')),
                ('vin', models.ForeignKey(db_column='vin', on_delete=django.db.models.deletion.DO_NOTHING, to='customer.kprcvehicle')),
            ],
            options={
                'db_table': 'kprc_rental_service',
            },
        ),
        migrations.CreateModel(
            name='KprcPayment',
            fields=[
                ('payment_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=30)),
                ('card_number', models.BigIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.kprcinvoice')),
            ],
            options={
                'db_table': 'kprc_payment',
            },
        ),
        migrations.AddField(
            model_name='kprcinvoice',
            name='rental_service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.kprcrentalservice'),
        ),
        migrations.CreateModel(
            name='KprcLocationclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='customer.kprcvehicleclass')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.DO_NOTHING, to='customer.kprclocation')),
            ],
            options={
                'db_table': 'kprc_locationclass',
                'unique_together': {('class_field', 'location')},
            },
        ),
        migrations.CreateModel(
            name='KprcCoupon',
            fields=[
                ('coupon_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('discount', models.SmallIntegerField()),
                ('validity', models.DateTimeField()),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.kprcindividual')),
            ],
            options={
                'db_table': 'kprc_coupon',
            },
        ),
        migrations.CreateModel(
            name='KprcCorporate',
            fields=[
                ('cust', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customer.kprccustomer')),
                ('employee_id', models.IntegerField()),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.kprccorporation')),
            ],
            options={
                'db_table': 'kprc_corporate',
            },
        ),
    ]
